#! /bin/sh

### BEGIN INIT INFO
# Provides:          NombreDelScript
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
start)
echo "Starting InKoutPi IU"
# run application you want to start
/home/pi/inKoutPi/initIU.sh
;;
stop)
echo "Stopping InKoutPi IU"
# kill application you want to stop
killall initIU.sh
;;
*)
echo "Usage: /etc/init.d/inkoutpiIU {start|stop}"
exit 1
;;
esac

exit 0
